<?php

class  Animal
{
    public $weight;

    public function eat()
    {
        var_dump("All animals can eat");
        return $this;
    }

    public function reproduce()
    {
        var_dump("All animals can reproduce");
        return $this;
    }
}

class Mammal extends Animal
{
    public $heartRate;

    public function breathe()
    {
        var_dump("I can breathe because I am a Mammal");
        return $this;
    }
}

class Dog extends Mammal
{
    public $color;

    public function bark()
    {
        var_dump("I can bark because I am a " . strtolower(get_class()));
        return $this;
    }

    public function chase()
    {
        var_dump("I am chasing a Rabbit");
        return $this;
    }

    public function breathe()
    {
        parent::breathe(); // TODO: Change the autogenerated stub
        var_dump("I breathe very fast");
        return $this;
    }

    public function __toString(): string
    {
        return "Weight: " . $this->weight . PHP_EOL . "Color: " . $this->color . PHP_EOL . "Heart Rate: " . $this->heartRate . PHP_EOL;

    }
}

$brown = new Dog; # can  write it instead of Dog()
$brown->weight = '7.3';
$brown->color = 'brown';
$brown->heartRate = 'okay';

echo $brown->__toString();

$brown->eat()
    ->reproduce()
    ->breathe()
    ->bark()
    ->chase();